tentativa

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -23,19 +23,18 @@ jobs:
         dotnet-version: 8.0.x
 
     - name: Restore dependencies
-      run: dotnet restore CreateContactMicroservice/CriarContatos.Api.sln
-
-    - name: Clean build directories
-      run: dotnet clean CreateContactMicroservice/CriarContatos.Api.sln
+      run: dotnet restore ContactAPI/FiapGrupo42Fase3.WebAPI.sln
 
     - name: Build
-      run: dotnet build CreateContactMicroservice/CriarContatos.Api.sln --no-restore --configuration Release
+      run: dotnet build ContactAPI/FiapGrupo42Fase3.WebAPI.sln --no-restore
 
     - name: Publish Build Artifacts
       uses: actions/upload-artifact@v4
       with:
         name: build-artifacts
-        path: CreateContactMicroservice/**/bin/Release/net8.0/
+        path: |
+          ContactAPI/FiapGrupo42Fase3.Test/bin/Debug/net8.0/
+          ContactAPI/FiapGrupo42Fase3.WebAPI/bin/Debug/net8.0/
 
   test:
     runs-on: ubuntu-latest
@@ -53,16 +52,53 @@ jobs:
       uses: actions/download-artifact@v4
       with:
         name: build-artifacts
-        path: CreateContactMicroservice/
+        path: .
 
     - name: Run all tests
-      run: dotnet test CreateContactMicroservice/CriarContatos.Api.sln --no-build --configuration Release --logger "trx;LogFileName=TestResults/test-results.trx"
+      run: dotnet test ContactAPI/FiapGrupo42Fase3.WebAPI.sln --no-build --verbosity normal --logger "trx;LogFileName=ContactAPI/FiapGrupo42Fase3.Test/TestResults/all-test-results.trx"
+
 
     - name: List Test Results
-      run: ls CreateContactMicroservice/CriarContatos.Test/TestResults || echo "Nenhum resultado encontrado."
+      run: |
+        echo "Verificando conteúdo do diretório TestResults:"
+        ls FiapGrupo42Fase3.Test/TestResults
 
     - name: Publish Test Results
       uses: actions/upload-artifact@v4
       with:
         name: test-results
-        path: CreateContactMicroservice/CriarContatos.Test/TestResults
+        path: FiapGrupo42Fase3.Test/TestResults
+
+  setup-monitoring:
+    runs-on: ubuntu-latest
+    needs: test
+
+    steps:
+    - name: Setup Prometheus
+      run: docker run -d --name prometheus -p 9090:9090 prom/prometheus
+
+    - name: Setup Grafana
+      run: docker run -d --name grafana -p 3000:3000 grafana/grafana
+
+    - name: Wait for Grafana to start 
+      run: |
+        for i in {1..10}; do
+          if curl -L -f http://localhost:3000 > /dev/null; then
+            echo "Grafana started"
+            exit 0
+          fi
+          echo "Waiting for Grafana..."
+          sleep 3
+        done
+        echo "Grafana failed to start"
+        exit 1
+
+    - name: Verify Prometheus 
+      run: curl -f http://localhost:9090/metrics || exit 1
+
+    - name: Verify Grafana
+      run: curl -L -f http://localhost:3000 > /dev/null || exit 1
+
+    - name: Grafana Error Logs
+      if: failure()
+      run: docker logs grafana
