tentativa

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -113,13 +113,13 @@ jobs:
           echo "HOST_IP=$HOST_IP" >> $GITHUB_ENV
           echo "Host IP: $HOST_IP"  # Log para depuração
 
-      # - name: Start RabbitMQ
-      #   run: |
-      #     docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
-      #     sleep 10 # Aguarda RabbitMQ subir
+      - name: Start RabbitMQ
+        run: |
+          docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
+          sleep 10 # Aguarda RabbitMQ subir
 
-      # - name: Verify RabbitMQ
-      #   run: curl -f http://localhost:15672 || exit 1
+      - name: Verify RabbitMQ
+        run: curl -f http://localhost:15672 || exit 1
 
       - name: Download Build Artifacts
         uses: actions/download-artifact@v4
@@ -130,22 +130,22 @@ jobs:
       - name: Debug File Structure
         run: ls -R .
 
-      # - name: Start API in Background
-      #   env:
-      #     ASPNETCORE_URLS: http://0.0.0.0:5102
-      #   run: |
-      #     cd CriarContatos.Api/bin/Release/net8.0/
-      #     dotnet CriarContatos.Api.dll &
-      #     for i in {1..10}; do
-      #       if curl -f http://localhost:5102/health > /dev/null 2>&1; then
-      #         echo "API started successfully"
-      #         exit 0
-      #       fi
-      #       echo "Waiting for API to start... Attempt $i of 10"
-      #       sleep 3
-      #     done
-      #     echo "API failed to start after 10 attempts"
-      #     exit 1
+      - name: Start API in Background
+        env:
+          ASPNETCORE_URLS: http://0.0.0.0:5102
+        run: |
+          cd CriarContatos.Api/bin/Release/net8.0/
+          dotnet CriarContatos.Api.dll &
+          for i in {1..10}; do
+            if curl -f http://localhost:5102/health > /dev/null 2>&1; then
+              echo "API started successfully"
+              exit 0
+            fi
+            echo "Waiting for API to start... Attempt $i of 10"
+            sleep 3
+          done
+          echo "API failed to start after 10 attempts"
+          exit 1
 
       - name: Setup Prometheus
         run: |
