tentativa

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -11,8 +11,26 @@ on:
       - main
 
 jobs:
+  setup-rabbitmq:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Start RabbitMQ
+        run: |
+          docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
+          for i in {1..10}; do
+            if curl -f http://localhost:15672 > /dev/null 2>&1; then
+              echo "RabbitMQ is up"
+              exit 0
+            fi
+            echo "Waiting for RabbitMQ... Attempt $i of 10"
+            sleep 3
+          done
+          echo "RabbitMQ failed to start"
+          exit 1
+
   build-and-restore:
     runs-on: ubuntu-latest
+    needs: setup-rabbitmq
     steps:
       - uses: actions/checkout@v4
 
@@ -35,18 +53,10 @@ jobs:
             Producer/CreateContact/CriarContatos.Test/bin/Release/net8.0/
             Producer/CreateContact/CriarContatos.Api/bin/Release/net8.0/
 
-  start-rabbitmq-and-api:
+  start-api:
     runs-on: ubuntu-latest
     needs: build-and-restore
     steps:
-      - name: Start RabbitMQ
-        run: |
-          docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
-          sleep 10 # Aguarda RabbitMQ subir
-
-      - name: Verify RabbitMQ
-        run: curl -f http://localhost:15672 || exit 1
-
       - uses: actions/checkout@v4
 
       - name: Download Build Artifacts
@@ -62,7 +72,7 @@ jobs:
         env:
           ASPNETCORE_URLS: http://localhost:5102
         run: |
-          cd CriarContatos.Api/bin/Release/net8.0/
+          cd Producer/CreateContact/CriarContatos.Api/bin/Release/net8.0/
           dotnet CriarContatos.Api.dll &
           for i in {1..10}; do
             if curl -f http://localhost:5102/health > /dev/null 2>&1; then
@@ -72,7 +82,7 @@ jobs:
             echo "Waiting for API to start... Attempt $i of 10"
             sleep 3
           done
-          echo "API failed to start after 10 attempts"
+          echo "API failed to start"
           exit 1
 
       - name: Test API Health
@@ -83,7 +93,7 @@ jobs:
 
   unit-tests:
     runs-on: ubuntu-latest
-    needs: start-rabbitmq-and-api
+    needs: start-api
     steps:
       - uses: actions/checkout@v4
 
@@ -113,14 +123,6 @@ jobs:
           echo "HOST_IP=$HOST_IP" >> $GITHUB_ENV
           echo "Host IP: $HOST_IP"  # Log para depuração
 
-      - name: Start RabbitMQ
-        run: |
-          docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
-          sleep 10 # Aguarda RabbitMQ subir
-
-      - name: Verify RabbitMQ
-        run: curl -f http://localhost:15672 || exit 1
-
       - name: Download Build Artifacts
         uses: actions/download-artifact@v4
         with:
@@ -134,7 +136,7 @@ jobs:
         env:
           ASPNETCORE_URLS: http://0.0.0.0:5102
         run: |
-          cd CriarContatos.Api/bin/Release/net8.0/
+          cd Producer/CreateContact/CriarContatos.Api/bin/Release/net8.0/
           dotnet CriarContatos.Api.dll &
           for i in {1..10}; do
             if curl -f http://localhost:5102/health > /dev/null 2>&1; then
@@ -144,7 +146,7 @@ jobs:
             echo "Waiting for API to start... Attempt $i of 10"
             sleep 3
           done
-          echo "API failed to start after 10 attempts"
+          echo "API failed to start"
           exit 1
 
       - name: Setup Prometheus
